### PR TITLE
Added instructions for installing Android Studio

### PR DESCRIPTION
**Pull request by KartikShankhavaram**

### CODE REVIEW

**Review by divyanshu-rawat — COMMENTED** [review]
wait for other reviewers to review. @saketkumar95 please review this.

**Review by saketkumar — APPROVED** [review]

**Comment by saketkumar** [comment]
Merged!
Thanks @KartikShankhavaram 👍

**Review by divyanshu-rawat — COMMENTED** [review]
thanks, @KartikShankhavaram  finally merged 👍

**Comment by KartikShankhavaram** [comment]
👍

**Pull request merged**
