### PR TITLE
Added two free courses

### PR DESCRIPTION
**Pull request by KartikShankhavaram**

### CODE REVIEW

**Review by divyanshu-rawat — CHANGES_REQUESTED** [review]
It would be great if instead of writing the entire URL you hyperlink it in the text itself.
For example - 
embed URL in the below-mentioned text.
Basic Android Layouts course on Udacity for beginners.

**Review by divyanshu-rawat — APPROVED** [review]

**Review by divyanshu-rawat — APPROVED** [review]
let's wait for other reviewers :) 
Thanks for the PR :+1:

**Review by gauravkulkarni96 — APPROVED** [review]

**Comment by saketkumar** [comment]
Actually I created this repo so that anyone can write something related to android they know, blog type. Not like just adding a link of the course. These links are very common to everyone and no one will come to this repo just to open that link. I'll be writing one soon so that you all get a rough idea on how to write blogs. These days writing blogs related to the technology you use is also great step towards learning. :)

**Comment by divyanshu-rawat** [comment]
@saketkumar95  thanks for the suggestion :+1:

**Pull request merged**
